language: node_js
node_js: 13
install:
  - npm ci
  - cd server-api
  - npm ci
  - cd ../client-app
  - npm ci
  - cd ..
before_script:
  - npm i-all
  - psql -c "create database travis_ci_test;" -U postgres
script:
  - npm run initdb && npm run travis-test
services:
  - postgresql
