language: node_js
node_js: 13
before_install:
  - npm i -g npm@6
install:
  - npm ci
  - cd wip-app
  - npm ci
  - cd ../wip-rest-api
  - npm ci
  - cd ..
before_script:
  - psql -c "create database travis_ci_test;" -U postgres
script:
  - npm run initdb && npm run travis-test
services:
  - postgresql
